# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mathieu Fortune [BETA]
email: pro.mathieu.fortune@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mathieu Fortune - Front-End Developer & UX/UI Designer sharing his passions by working between humans on interesting projects.
  This website is still in development and will be update frequently. It's built with Jekyll, Sass and love <3. Sources on GitHub
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mathieufortune.github.com" # the base hostname & protocol for your site
twitter_username: MsterMF
github_username:  MathieuFortune
feed_description: Mathieu Fortune - Front-End Developer & UX/UI Designer sharing his passions by working between humans on interesting projects. # RSS feed site description
rss_path: feed.xml

# Build settings
markdown: kramdown
sass:
    style: compressed
