# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Mathieu Fortune
  fr: Mathieu Fortune
title_head:
  en: Mathieu Fortune| Front-end Developer, UX Designer & Entrepreneur sharing his passion for the web.
  fr: Mathieu Fortune| Front-end Developer, UX Designer & Entrepreneur partageant sa passion pour le web.
email: pro.mathieu.fortune@gmail.com
description:
  en: Mathieu Fortune - Front-End Developer & UX/UI Designer sharing his passions by working between humans on interesting projects. Website built with Jekyll, Sass and love <3. Sources on GitHub
  fr: Mathieu Fortune - Front-End Developer & UX/UI Designer partageant ses passions en travaillant entre humains sur des projets intéressant. Site web monté avec Jekyll, Sass et amour <3. Sources sur GitHub
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
feed_description: Mathieu Fortune - Front-End Developer & UX/UI Designer sharing his passions by working between humans on interesting projects. # RSS feed site description
logo: /images/logo.png

made_with:
  en: Made with Jekyll, Sass and love <3.
  fr: Fait avec Jekyll, Sass and love <3.

contact:
  item_menu:
    en: Contact
    fr: Contact
  mailto:
    en: mailto:pro.mathieu.fortune@gmail.com?subject=Hello from your portfolio !&amp;body=Hi Mathieu, I was just browsing your portfolio and...
    fr: "mailto:pro.mathieu.fortune@gmail.com?subject=Hello du portfolio !&amp;body=Bonjour Mathieu, j'étais en train de visiter ton portfolio et..."

rss_path: feed.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mathieufortune.github.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: none

twitter_username: MsterMF
github_username:  MathieuFortune
linkedin_username: mathieu-fortune-220268101
codepen_username: mathieu_fortune
youtube_username: Ubeure

google_analytics: UA-78886688-1

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#sass:
style: compressed
